apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seif
resources:
  - namespace.yaml
  - app.yaml
  - redis.yaml
  - policies.yaml
  - network-policies.yaml
configMapGenerator:
  - name: redis-scripts
    files:
      - scripts/common.sh
      - scripts/start-redis.sh
      - scripts/start-sentinel.sh
      - scripts/health.sh
generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/part-of: seif
