apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: seif
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-to-redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: seif-api
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: client
              app.kubernetes.io/part-of: seif
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: seif-redis
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 26379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-peers-and-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: seif-redis
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: seif-api
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: seif-redis
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 26379
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: seif-redis
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 26379
