apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seif
resources:
  - ../local
  - runtime-class.yaml
  - volumes.yaml
configMapGenerator:
  - name: seif-policies
    behavior: replace
    files:
      - policies.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: seif-api
    newName: seif-api
    newTag: local-be55982
  - name: seif-ner
    newName: seif-ner
    newTag: rubert-be55982
patches:
  - path: api-patch.yaml
  - path: ner-patch.yaml
  - path: service-patch.yaml
