#!/bin/sh
set -eu
umask 077

: "${POD_NAME:?}" "${POD_NAMESPACE:?}" "${REDIS_PASSWORD:?}"
CLUSTER_DOMAIN=${CLUSTER_DOMAIN:-cluster.local}
MASTER_NAME=${MASTER_NAME:-seif-master}
SELF="${POD_NAME}.redis-headless.${POD_NAMESPACE}.svc.${CLUSTER_DOMAIN}"
export REDISCLI_AUTH="$REDIS_PASSWORD"

# Secrets are generated by create-secrets.py; reject config-file injection.
case "$REDIS_PASSWORD" in
  ''|*[!A-Za-z0-9_-]*) echo 'Redis password must be nonempty base64url/hex text' >&2; exit 64 ;;
esac
case "$POD_NAME" in redis-0|redis-1|redis-2) ;; *) echo 'Exactly three fixed Redis members are supported' >&2; exit 64 ;; esac

peer_name() { printf 'redis-%s.redis-headless.%s.svc.%s' "$1" "$POD_NAMESPACE" "$CLUSTER_DOMAIN"; }

# Return a master only when at least $1 distinct Sentinel endpoints agree.
# Never infer a primary from pod ordinal or from a lone stale Sentinel.
discover_master() {
  required=$1
  vote0=0; vote1=0; vote2=0
  for ordinal in 0 1 2; do
    response=$(timeout 2 redis-cli --raw -h "$(peer_name "$ordinal")" -p 26379 \
      SENTINEL get-master-addr-by-name "$MASTER_NAME" 2>/dev/null) || continue
    selected=$(printf '%s\n' "$response" | sed -n '1p' | tr -d '\r')
    port=$(printf '%s\n' "$response" | sed -n '2p' | tr -d '\r')
    [ "$port" = 6379 ] || continue
    if [ "$selected" = "$(peer_name 0)" ]; then vote0=$((vote0 + 1)); fi
    if [ "$selected" = "$(peer_name 1)" ]; then vote1=$((vote1 + 1)); fi
    if [ "$selected" = "$(peer_name 2)" ]; then vote2=$((vote2 + 1)); fi
  done
  if [ "$vote0" -ge "$required" ]; then peer_name 0; return 0; fi
  if [ "$vote1" -ge "$required" ]; then peer_name 1; return 0; fi
  if [ "$vote2" -ge "$required" ]; then peer_name 2; return 0; fi
  return 1
}

bootstrap_allowed() { [ "$(cat /bootstrap/allow 2>/dev/null || true)" = true ]; }
