apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seif
resources:
  - ../hybrid
  - redis-pvs.yaml
images:
  - name: ghcr.io/l0ckr/seif-pii
    newName: seif-api
    newTag: local-2e9076e
  - name: ghcr.io/l0ckr/seif-pii-ner
    newName: seif-ner
    newTag: local-2e9076e
patches:
  - target:
      kind: StatefulSet
      name: redis
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: ""
