apiVersion: v1
kind: PersistentVolume
metadata:
  name: seif-local-redis-0
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: seif
    name: data-redis-0
  local:
    path: /var/local/seif/redis-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [seif-control-plane]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seif-local-redis-1
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: seif
    name: data-redis-1
  local:
    path: /var/local/seif/redis-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [seif-control-plane]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seif-local-redis-2
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: seif
    name: data-redis-2
  local:
    path: /var/local/seif/redis-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [seif-control-plane]
